name: ☃ build-and-test
on:
  push:
    paths-ignore:
      - '*.md'
  workflow_dispatch:

env:
  REPO_NAME: te-cdn-packages

defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      JOBNAME: build-and-test
    strategy:
      fail-fast: false
      matrix:
        include:
          - GCCVERSION: 8
            IMAGE_TAG: u18g8

    container: 
      env:
        BUILDER: ci-at-${{ github.head_ref || github.ref_name }}
        VERSION: ${{ github.run_id }}
        GCCVERSION: ${{ matrix.GCCVERSION }}
        CPU_NATIVE: false
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        TE_LIBS: /opt/mazoea/installation
      image: ghcr.io/mazoea/docker-ci-build:${{ matrix.IMAGE_TAG }}
    steps:
      - uses: mazoea/ga-maz/start@master
        with:
          MS_TEAMS_URI: ${{ secrets.MS_DQ_TEAMS_WEBHOOK_URI }}

      - uses: actions/checkout@v3

      - name: build
        working-directory: scripts
        run: |
          ./os.specific.sh
          ./build.sh

      - uses: mazoea/ga-maz/end@master
        with:
          MS_TEAMS_URI: ${{ secrets.MS_DQ_TEAMS_WEBHOOK_URI }}
        if: ${{ always() }}
